# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!
import sys
from PyQt5 import QtCore, QtGui, QtWidgets,QtWidgets
from PyQt5.QtWidgets import QInputDialog,QMainWindow,QPushButton,QApplication
from algorithm_python import al_001
class Dialog1(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(859, 639)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 20, 95, 32))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(260, 10, 113, 44))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 20, 331, 32))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 95, 32))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 100, 95, 32))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(560, 100, 95, 32))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 170, 160, 44))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 240, 160, 44))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 310, 160, 44))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 380, 160, 44))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 450, 160, 44))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 510, 160, 44))
        self.pushButton_6.setObjectName("pushButton_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(240, 160, 260, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(240, 230, 260, 51))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(240, 300, 260, 51))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(240, 370, 260, 51))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(240, 440, 260, 51))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(240, 510, 260, 51))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_7.setGeometry(QtCore.QRect(560, 160, 260, 51))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_8.setGeometry(QtCore.QRect(560, 230, 260, 51))
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_9.setGeometry(QtCore.QRect(560, 300, 260, 51))
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_10.setGeometry(QtCore.QRect(560, 370, 260, 51))
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_11.setGeometry(QtCore.QRect(560, 440, 260, 51))
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_12.setGeometry(QtCore.QRect(560, 510, 260, 51))
        self.textBrowser_12.setObjectName("textBrowser_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 859, 38))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.onChanged)
        self.pushButton_2.clicked.connect(self.onChanged)
        self.pushButton_3.clicked.connect(self.onChanged)
        self.pushButton_4.clicked.connect(self.onChanged)
        self.pushButton_5.clicked.connect(self.onChanged)
        self.pushButton_6.clicked.connect(self.onChanged)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fibonacci_Experiment"))
        self.label.setText(_translate("MainWindow", "       第"))
        self.label_2.setText(_translate("MainWindow", "个斐波那契数"))
        self.label_3.setText(_translate("MainWindow", "方法："))
        self.label_4.setText(_translate("MainWindow", "结果:"))
        self.label_5.setText(_translate("MainWindow", "时间(s):"))
        self.pushButton.setText(_translate("MainWindow", "迭代法"))
        self.pushButton_2.setText(_translate("MainWindow", "递归法"))
        self.pushButton_3.setText(_translate("MainWindow", "优化迭代法"))
        self.pushButton_4.setText(_translate("MainWindow", "迭代法(最大)"))
        self.pushButton_5.setText(_translate("MainWindow", "递归法(最大)"))
        self.pushButton_6.setText(_translate("MainWindow", "优化迭代法(最大)"))

    def onChanged(self):
            a = al_001.Solution()
            number = self.lineEdit.text()
            sender = self.sender()
            if sender == self.pushButton:
                self.textBrowser.clear()
                self.textBrowser.append(str(a.FibonacciOF(int(number))))
                self.textBrowser_7.append(str(a.Old_Time_Fib(int(number))))
            elif sender == self.pushButton_2:
                self.textBrowser_2.clear()
                self.textBrowser_2.append(str(a.FibonacciD(int(number))))
                self.textBrowser_8.append(str(a.Time_interation(int(number))))
            elif sender == self.pushButton_3:
                self.textBrowser_3.clear()
                self.textBrowser_9.clear()
                self.textBrowser_3.append(str(a.FibonacciF(int(number))))
                self.textBrowser_9.append(str(a.New_Time_Fib(int(number))))
            elif sender == self.pushButton_4:
                self.textBrowser_4.clear()
                self.textBrowser_10.clear()
                self.textBrowser_4.append(str(a.FibonacciOF(int(92))))
                self.textBrowser_10.append(str(a.Old_Time_Fib(int(92))))
            elif sender == self.pushButton_5:
                self.textBrowser_5.clear()
                self.textBrowser_11.clear()
                self.textBrowser_5.append(str(a.FibonacciD(int(92))))
                self.textBrowser_11.append(str(a.Time_interation(int(92))))
            else:
                self.textBrowser_6.clear()
                self.textBrowser_12.clear()
                self.textBrowser_6.append(str(a.FibonacciF(int(92))))
                self.textBrowser_12.append(str(a.New_Time_Fib(int(92))))